general.import = ["~/.config/omarchy/current/theme/alacritty.toml"]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "JetBrainsMono Nerd Font" }
bold = { family = "JetBrainsMono Nerd Font" }
italic = { family = "JetBrainsMono Nerd Font" }
size = 14

[window]
padding.x = 14
padding.y = 14
decorations = "None"
opacity = 0.85

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen" }]
