# Global Ruff Configuration
# Save this as: ~/.config/ruff/ruff.toml

line-length = 88
target-version = "py38"

exclude = [
  ".git",
  ".mypy_cache",
  ".ruff_cache",
  ".venv",
  "__pycache__",
  "build",
  "dist",
  "venv",
  "node_modules",
]

[lint]
select = [
  "E",   # pycodestyle errors
  "W",   # pycodestyle warnings  
  "F",   # Pyflakes
  "I",   # isort
  "B",   # flake8-bugbear
  "C4",  # flake8-comprehensions
  "UP",  # pyupgrade
  "SIM", # flake8-simplify
  "N",   # pep8-naming
  "RUF", # Ruff-specific rules
  "A",   # flake8-builtins
  "COM", # flake8-commas
  "G",   # flake8-logging-format
  "PIE", # flake8-pie
  "Q",   # flake8-quotes
  "RET", # flake8-return
  "ARG", # flake8-unused-arguments
  "PTH", # flake8-use-pathlib
  "ERA", # eradicate
]

ignore = [
  "E501",   # Line too long (handled by formatter)
  "COM812", # Trailing comma missing (conflicts with formatter)
  "ISC001", # Implicitly concatenated string literals (conflicts with formatter)
]

fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[lint.isort]
split-on-trailing-comma = true

[lint.mccabe]
max-complexity = 10

[lint.per-file-ignores]
"**/tests/**/*" = ["S101", "T201"] # Allow assertions and prints in tests
"**/test_*.py" = ["S101", "T201"]  # Allow assertions and prints in test files
"__init__.py" = ["F401"]           # Allow unused imports in __init__.py
"**/scripts/**/*" = ["T201"]       # Allow prints in scripts

[lint.flake8-quotes]
docstring-quotes = "double"
