#!/bin/bash

# Rofi Wallpaper Picker with Preview for Hyprpaper & Hyprlock
# Dependencies: rofi, imagemagick, hyprpaper, hyprlock

# Configuration
WALLPAPER_DIR="$HOME/Images"
HYPRPAPER_CONFIG="$HOME/.config/hypr/hyprpaper.conf"
HYPRLOCK_CONFIG="$HOME/.config/hypr/hyprlock.conf"
CACHE_DIR="$HOME/.cache/wallpaper-picker"
THEME_FILE="$HOME/.config/rofi/launchers/wallpapers/wallpicker-nord.rasi"
THUMBNAIL_SIZE="314x144"

# Create cache directory if it doesn't exist
mkdir -p "$CACHE_DIR"
mkdir -p "$(dirname "$THEME_FILE")"

# Check if wallpaper directory exists
if [[ ! -d "$WALLPAPER_DIR" ]]; then
  notify-send "Error" "Wallpaper directory not found: $WALLPAPER_DIR" -u critical
  exit 1
fi

# Find all image files
mapfile -t wallpapers < <(find "$WALLPAPER_DIR" -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.webp" \) | sort)

if [[ ${#wallpapers[@]} -eq 0 ]]; then
  notify-send "Error" "No wallpapers found in $WALLPAPER_DIR" -u critical
  exit 1
fi

# Create a temporary file for rofi input
temp_file=$(mktemp)

# Generate thumbnails and create menu entries
for wp in "${wallpapers[@]}"; do
  name=$(basename "$wp")
  # Generate thumbnail path
  thumb="$CACHE_DIR/$(echo "$name" | md5sum | cut -d' ' -f1).png"

  # Create thumbnail if it doesn't exist or is older than original
  if [[ ! -f "$thumb" ]] || [[ "$wp" -nt "$thumb" ]]; then
    convert "$wp" -resize "${THUMBNAIL_SIZE}^" -gravity center -extent "$THUMBNAIL_SIZE" "$thumb" 2>/dev/null
    if [[ $? -ne 0 ]]; then
      echo "Warning: Failed to create thumbnail for $name" >&2
      continue
    fi
  fi

  # Format: name\0icon\x1fpath\n
  printf "%s\0icon\x1f%s\n" "$name" "$thumb" >>"$temp_file"
done

# Show rofi menu with theme
selected=$(cat "$temp_file" | rofi -dmenu -i \
  -p "Select Wallpaper" \
  -theme "$THEME_FILE" \
  -show-icons \
  -format "s")

# Clean up temp file
rm -f "$temp_file"

# Exit if nothing selected
[[ -z "$selected" ]] && exit 0

# Find the full path of selected wallpaper
selected_path=""
for wp in "${wallpapers[@]}"; do
  if [[ "$(basename "$wp")" == "$selected" ]]; then
    selected_path="$wp"
    break
  fi
done

if [[ -z "$selected_path" ]]; then
  notify-send "Error" "Could not find selected wallpaper" -u critical
  exit 1
fi

echo "Selected wallpaper: $selected_path"

# Get all monitors
monitors=$(hyprctl monitors -j | jq -r '.[].name' 2>/dev/null)

if [[ -z "$monitors" ]]; then
  echo "Warning: Could not detect monitors, using fallback configuration"
  monitors=""
fi

# Create new hyprpaper config using the modern wallpaper block format
cat >"$HYPRPAPER_CONFIG" <<EOF
# Generated by wallpaper-picker
# $(date)

EOF

# Add wallpaper block for each monitor
if [[ -n "$monitors" ]]; then
  for monitor in $monitors; do
    cat >>"$HYPRPAPER_CONFIG" <<EOF
wallpaper {
    monitor = $monitor
    path = $selected_path
    fit_mode = cover
}

EOF
  done
fi

# Add fallback wallpaper block (empty monitor means fallback)
cat >>"$HYPRPAPER_CONFIG" <<EOF
wallpaper {
    monitor = 
    path = $selected_path
    fit_mode = cover
}

splash = false
EOF

echo "Updated hyprpaper.conf"

# Reload hyprpaper using IPC
if pgrep -x hyprpaper >/dev/null; then
  echo "Reloading hyprpaper via IPC..."

  # Set wallpaper for each monitor
  if [[ -n "$monitors" ]]; then
    for monitor in $monitors; do
      hyprctl hyprpaper wallpaper "$monitor,$selected_path,cover" 2>/dev/null
    done
  fi

  # Set fallback wallpaper
  hyprctl hyprpaper wallpaper ",$selected_path,cover" 2>/dev/null
else
  echo "Starting hyprpaper..."
  hyprpaper &
fi

# Update hyprlock config
if [[ -f "$HYPRLOCK_CONFIG" ]]; then
  # Replace path in background section
  sed -i "s|^\s*path\s*=.*|    path = $selected_path|g" "$HYPRLOCK_CONFIG"
else
  # Create basic hyprlock config with background
  cat >"$HYPRLOCK_CONFIG" <<EOF
background {
    monitor =
    path = $selected_path
    blur_passes = 2
    blur_size = 7
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}
EOF
fi

echo "Updated hyprlock.conf"

notify-send "Wallpaper Changed" "Set to: $(basename "$selected_path")" -i "$selected_path"
