# Main apps
$terminal = GTK_IM_MODULE=simple ghostty
$fileManager = cosmic-files
# $menu = hyprlauncher
# $menu = rofi -show drun
$menu = ~/.config/rofi/launchers/type-3/launcher.sh || pkill rofi
$browser = uwsm app zen-browser
$browser_incognito = uwsm app -- zen-browser --private-window
$browser_tor = uwsm app -- brave --tor

# Autostart apps
# all are nadled by uwsm: systemctl --user enable --now {app}.service
# app: waybar, swaync, hypridle, hyprsunset, hyprpaper
exec-once = arch-update -c
