# Main apps
$terminal = GTK_IM_MODULE=simple ghostty
$fileManager = cosmic-files
# $menu = hyprlauncher
# $menu = rofi -show drun
$menu = ~/.config/rofi/launchers/type-3/launcher.sh || pkill rofi
$browser = uwsm app brave
$browser_incognito = uwsm app -- brave --incognito


# Autostart apps
exec-once = uwsm app waybar
# exec-once = swww-daemon
# exec-once = uwsm app hyprpaper
exec-once = uwsm app swaync
exec-once = uwsm app hypridle
exec-once = uwsm app hyprsunset
