ecosystem {
  enforce_permissions = 1
}

permission = /usr/bin/hyprlock, screencopy, allow
permission = /usr/bin/grim, screencopy, allow
permission = /usr/lib/xdg-desktop-portal-hyprland, screencopy, allow
permission = /usr/bin/hyprpm, plugin, allow
