# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrules that are useful

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

# Float impala and position it in top-right corner
windowrule {
    name = netpala-float
    match:title = ^(netpala)$
    float = true
    size = 1200 1000

}

# Float bluetui and position it in top-right corner
windowrule {
    name = blutui-float
    match:title = ^(bluetui)$
    float = true
    size = 900 1000
}

# Float wiremix and position it in top-right corner
windowrule {
    name = wiremix-float
    match:title = ^(wiremix)$
    float = true
    size = 1200 800
}

windowrule {
    name = cosmic-float
    match:class = ^(com.system76.CosmicFilesDialog)$
    float = true
    center = true
}

windowrule {
    name = steam-float
    match:title = ^(Friend List)$
    float = true
    center = true
}
