font_family       IosevkaTerm Nerd Font Mono
font_size         16.0
disable_ligatures never

url_style            curly
open_url_with        default
detect_url           yes
underline_hyperlinks hover

copy_on_select  yes

background_opacity 0.95
window_padding_width    16
hide_window_decorations yes

allow_remote_control yes
include current-theme.conf
